# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-02 15:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210702_1530'),
    ]

    operations = [

        migrations.AlterField(
            model_name='blog',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),

    ]
